
version: '3.3'
services:
  qq:
    image: bestwu/qq:latest
    container_name: qq
    devices:
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./Technology/TencentFiles:/TencentFiles
    environment:
      - DISPLAY=unix$DISPLAY
      - AUDIO_GID=29
      - XMODIFIERS=@im=ibus
      - GID=$GID
      - UID=$UID

  lantern:
    image: wilon/lantern:latest
    container_name: lantern
    restart: always
    ports:
      - "3128:3128"
      - "8090:8080"

  zeronet:
    image: nofish/zeronet:latest
    container_name: zeronet
    restart: always
    ports:
      - "15441:15441"
      - "43110:43110"
    volumes:
      - ./Technology/zeronet_date:/root/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./Technology/mongoData/db:/data/db
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./Technology/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: '123'
       MYSQL_DATABASE: 'database'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: '123'

